import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// export const metadata: Metadata = {
//   title: "ShareFare | Travel Together, Travel Smarter",
//   description: "Generated by create next app",
// };
export const metadata = {
  metadataBase: new URL('https://sharefare.com'),

  title: {
    default: 'ShareFare',
    template: '%s | ShareFare',
  },

  description:
    'Affordable carpooling and ride sharing platform connecting commuters across cities.',

  keywords: [
    'carpool',
    'ride sharing',
    'car pooling app',
    'shared rides',
    'commuter rides',
  ],

  robots: {
    index: true,
    follow: true,
  },
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: 'any' },
      { url: '/icon.png', type: 'image/png', sizes: '512x512' },
    ],
    shortcut: '/favicon.ico',
    apple: '/apple-touch-icon.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}
